### ISSUE TITLE
IAM Policy update does not provide a way to specify the request payload

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#150]
Similar to #140

Same story as #149 - it takes an array of json objects as request payload:

- Silo-level
```
$ oxide policy update -h
Update the current silo's IAM policy

Usage: oxide policy update

Options:
  -h, --help  Print help

$ oxide api /v1/policy
{
  "role_assignments": [
    {
      "identity_id": "12cc9827-caf3-4590-bfca-58d06af0be0c",
      "identity_type": "silo_group",
      "role_name": "admin"
    },
    {
      "identity_id": "8e2bdf35-f55f-4bb6-a8c7-c21b1b4b8e84",
      "identity_type": "silo_group",
      "role_name": "viewer"
    }
  ]
}
```
- Project-level
```
$ oxide project policy update -h
Update a project's IAM policy

Usage: oxide project policy update --project <project>

Options:
      --project <project>  Name or ID of the project
  -h, --help               Print help

$ oxide api /v1/projects/prom-dev/policy
{
  "role_assignments": [
    {
      "identity_id": "8e2bdf35-f55f-4bb6-a8c7-c21b1b4b8e84",
      "identity_type": "silo_group",
      "role_name": "collaborator"
    }
  ]
}
```

**Comment by ahl** [comment]
I'm not sure how to best represent this in the CLI, but maybe something like this:

```
oxide policy update \
    --role-assignment 8e2bdf35-f55f-4bb6-a8c7-c21b1b4b8e84:silo_group:admin \
    --role-assignment 8e2bdf35-f55f-4bb6-a8c7-c21b1b4b8e84:silo_group:viewer
```

What do you think?

**Comment by david-crespo** [comment]
I don't like it. I lean toward sticking to the JSON.

Because this endpoint replaces the entire policy, in practice the way this is used is: you download the current policy, modify it (e.g., add a new entry to the list), and send the entire thing back. That is very painful with this API because you'd have to write out the entire existing policy in this format.

I think this API would make more sense if we want to be cute like the console and do that work for the user, e.g., by having an `add` command that takes the single entry you want to add. But I'm not really advocating for that path either.

**Comment by ahl** [comment]
Ok, so maybe this is an example of a CLI subcommand where --json-body is going to be the only way to use it properly. Progenitor "knows" when it hasn't covered all mandatory parameters. In those cases we can make --json-body required. If we go in and make a simpler interface by hand we can also make --json-body optional.

**Comment by karencfv** [comment]
Generally I'm not a fan of reading a file from the CLI because of the shell command history. In this case though, I believe it would make for a better experience. Something like `$ oxide policy update --roles-file role-assignment.json` would simplify things a tad.

Telling users to write JSON directly on the terminal irks me a bit tbh.

**Comment by askfongjojo** [comment]
Taking `--json-body` input sounds reasonable. Even better if it can take json file input as @karencfv suggested.

**Comment by ahl** [comment]
Yes, `--json-body` would take a file (or a `<<EOF` here statement if you wanted to type it inline or take is from stdin)

**Comment by askfongjojo** [comment]
The `--json-body` param is the good-enough solution for now. If we decide to enhance it further, we can track the specific work with some new ticket. This one can be closed.
