### ISSUE TITLE
Device verification URL does not take into account the silo and IdP

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#60]
The process for generating an Oxide token via `oxide auth login` requires the user to verify the device by 1) logging into the console, 2) clicking "Log in on device" on a web page. The URL used to open the console web page assumes the "root" level login endpoint which would only work for the rack administrator. This is how the URL looks like currently:

http://127.0.0.1:8080/device/verify?user_code=NNNH-RTTG (if the user already has an active console session)
or
http://127.0.0.1:8080/spoof_login?state=%2Fdevice%2Fverify%3Fuser_code%3DNNNH-RTTG (if user hasn't logged into console)

The command should perhaps prompt for a silo (or take a silo param) so that it can look up the Silo IdP configuration and generate an appropriate URL, i.e.:
`<OXIDE_HOST>/login/<silo>/saml/<provider>`
or
`<OXIDE_HOST>/login/<silo>/local`

cc @ahl

**Comment by askfongjojo** [comment]
RFD 357 indicates that the silo DNS name will have the silo context embedded in it. If the OXIDE_HOST is set to the DNS name and the device verification endpoint can be redirected/rewritten to the silo-specific auth endpoint, the issue reported here will not be relevant any more. If it doesn't, the auth command still needs to prompt for a silo name (it cannot use the subdomain to derive the silo name because it appears to be customizable).

**Comment by ahl** [comment]
@plotnick can you help me understand how silos and OAuth are meant to interact? I'm not sure @askfongjojo's proposed solution with regard to the login URL is viable, but I don't understand enough of this oauth dance to be certain.

**Comment by plotnick** [comment]
As I recall, that part of the design was never finalized, so while I'm happy to try to help, I don't think anyone (including myself) has yet had a clear picture of exactly how silos and OAuth should interact. I also have not been closely following the recent RFD 357 work.

That said, I believe that the intention was, as @askfongjojo suggests, to rely on the external DNS name fo the `OXIDE_HOST` to determine the silo on the server side. I don't think that the client-side code should ever need the silo explicitly. If the initial device auth request is to `silo.company.com` , then the server can and should (but does not currently) produce a login URI specific to `silo` (using whatever mappings it has between DNS hosts and silos). The point is that since it's the server that generates and serves the login URI, we can customize it based on where the initial device auth request was received.

The code that should do this is in `nexus/src/external_api/device_auth.rs`, in particular the calls to `console_index_or_login_redirect`. See also [this `TODO`](https://github.com/oxidecomputer/omicron/blob/f83c7c65a8e54f03713ea226b86984f2d3096cfb/nexus/src/external_api/console_api.rs#L564). I am happy to help with this, but permission slip will probably continue to eat all my available cycles until roughly PVT RTM. @david-crespo and @davepacheco might also have more information or ideas about how this should go.

**Comment by askfongjojo** [comment]
The issue is no longer valid with changes made to auto direct user to the correct login endpoint based on the per-silo DNS .
