### ISSUE TITLE
Serial console command always follows output

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/oxide.rs#667]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

This was reported by a preview rack user:

The CLI serial console continued to follow output when the -m argument was supplied. The expectation was to be able to output a specific set of data and capture it to a file.

### What is the current behaviour and what actions did you take to get there

User report:
The CLI follows the console output by default and when I provide the --most-recent flag it says it defaults to 262144 but running the command still requires me to specify a number (it doesn't use the default). I was trying to save the output to a file (no follow) but even when specifying -m it still follows the output.

### CLI or SDK version

unknown

### Operating system

unknown

![serial-console](https://github.com/oxidecomputer/oxide.rs/assets/1377730/e724ef5a-889b-42b0-b335-79d13c318e99)

**Comment by lifning** [comment]
you may be looking for `oxide instance serial history` (rather than `console`) if you don't want it to follow!
i'll see about adding to each subcommand's --help description an unobtrusive mention of the other's existence.

~~the improper default value handling seems like a bug though, i'll take a look at that too~~ (edit: didn't notice 'til later, the `-m` flag is being passed when it should be omitted entirely for what the user wants here)

**Comment by lifning** [comment]
oh, i see - the "still requires me to specify a number (it doesn't use the default)" is because `-m` was being passed without an argument (seen in the screenshot). the correct thing to do is to delete the `-m` if you're not going to specify a number after it, so it uses the default.

**Comment by lifning** [comment]
marking this as closed now that additional clarification has been added to the docs.
