### ISSUE TITLE
CLI delete resource returns null

### ISSUE THREAD

**Issue by dwradcliffe** [oxidecomputer/oxide.rs#672]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

Response should be some kind of confirmation that the silo was deleted, or possibly the values from the deleted silo.

### What is the current behaviour and what actions did you take to get there

The delete command returns `null` even if it is successful.

```
$ oxide silo delete --silo testing
null
```

### CLI or SDK version

Oxide CLI 0.5.0+20240502.0

### Operating system

Mac OS

**Comment by david-crespo** [comment]
I think this comes from the principle that we return the raw JSON so that the output is parseable, but we could either 

- put that behavior behind a flag
- add a flag to show more metadata about the response (may already exist)
- handle 204s (or deletes) specially

**Comment by dwradcliffe** [comment]
Would it be better to just respond differently from nexus?

**Comment by dwradcliffe** [comment]
Actually yeah I confirmed that it's all deletes

```
❯ oxide vpc subnet delete --subnet=918b72e8-00f8-47a9-848e-f8c0333beba7
null
❯ oxide vpc delete --project=test1 --vpc=default
null
❯ oxide project delete --project=test1
null
```

**Comment by ahl** [comment]
Thanks for filing this @dwradcliffe. This is a bug. Irrespective of the the interface, the CLI needs to product output that indicates clear success or failure.

**Comment by david-crespo** [comment]
My sense was that a 204 No Content is an idiomatic response for a delete, so the issue here is really how the CLI chooses to print that result. With the other clients you’d be looking at the status on the response before looking at the body anyway, so the confusion about null is unlikely to arise. So I would try to fix this here before changing the API behavior.

Edit: I typed that out before I saw Adam’s response and now it looks a little silly.
