### ISSUE TITLE
ssh tunnel to /device/verify is redirected to the / recovery login

### ISSUE THREAD

**Issue by ubedan** [oxidecomputer/oxide.rs#687]
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

Expected that the ssh tunnel request:

http://localhost:1234/device/verify 

would display a page asking for the code indicated by:

oxide auth login --host http://192.168.1.24
Open this URL in your browser:
  http://192.168.1.24/device/verify

Enter the code: SCXL-NHTW

### What is the current behaviour and what actions did you take to get there

Instead, I go to the root recovery browser login page requiring a recovery username/password:

and the browser url is replaced with:

http://localhost:1234/login/recovery/local?redirect_uri=%2Fdevice%2Fverify

### CLI or SDK version

0.5.0+20240502.0 Circa 5/19

### Operating system

Helios

### Anything else you would like to add?

Small documentation issue:

On https://github.com/oxidecomputer/omicron/blob/main/docs/how-to-run.adoc
in the Using Omicron section there's an example using dig to get the nexux ip. 

Result:  192.168.1.21

Current default installations have shifted that due to a 2nd dns address, a different result:
192.168.1.22
192.168.1.23
192.168.1.24

As you follow through the text, 

The ssh tunnel section switches to the now appropriate 192.168.1.22:

"ssh -L 1234:192.168.1.22:80 dunkin.eng.oxide.computer

The above command configures ssh to bind to the TCP port 1234 on the machine running the browser, forward packets through the ssh connection, and redirect them to 192.168.1.22 port 80 as seen from the other side of the connection."

Other documentation on the page continues to reference the 192.168.1.21 address.

Please advise the best place to make future documentation suggestions. (And thanks in advance)

**Comment by david-crespo** [comment]
Hi! For a change to the documentation in the omicron repo, you could just make a PR in Omicron.

For the main problem here, let me explain what the intended behavior is. The reason you're not seeing the device code entry screen is that you're not logged into whatever silo it is deciding you're in. In order to enter the device code, you have to have a session in the console, which is then used to authenticate your device.

Authentication has to happen in a particular silo, and in production, figuring out which silo you're talking about is done by subdomain: each silo gets its own subdomain, and there is no way to make a request to nexus without a silo subdomain, so there is never any ambiguity about which silo is intended. For a local setup, there is no subdomain to tell it which silo, so it seems to be falling back to the recovery silo. Someone else might have to weigh in here — I'm not sure how to make it pick a different silo for this purpose when you're hitting localhost. You may be able to get it to pick a different silo (if that's what you want) through the URL authority or the Host header. Here is the relevant API code:

* [`/device/verify` definition](https://github.com/oxidecomputer/omicron/blob/82c77f2751c57f3dc9560eea79657871ba1bafc9/nexus/src/external_api/device_auth.rs#L105-L121)
* [Login redirect logic](https://github.com/oxidecomputer/omicron/blob/82c77f2751c57f3dc9560eea79657871ba1bafc9/nexus/src/external_api/console_api.rs#L598-L602) resulting in redirect to `/login/recovery/local`
* [`endpoint_for_request`](https://github.com/oxidecomputer/omicron/blob/82c77f2751c57f3dc9560eea79657871ba1bafc9/nexus/src/app/external_endpoints.rs#L671-L688)
* [`authority_for_request`](https://github.com/oxidecomputer/omicron/blob/82c77f2751c57f3dc9560eea79657871ba1bafc9/nexus/src/app/external_endpoints.rs#L698)

In any case, this is not a CLI issue even though it manifested through your use of the CLI. If we can figure out a more concrete version of the issue, it would make sense to reopen this as an issue in omicron.

**Comment by ubedan** [comment]
Just to add context... I'm attempting to follow the instructions for "Using Omicron" in 
https://github.com/oxidecomputer/omicron/blob/main/docs/how-to-run.adoc
and the instructions seemed to me to imply that device/verify was the procedure to setup the recovery credentials.

**Comment by david-crespo** [comment]
I see. Yeah, that seems like a documentation issue. It is not clear to me from the doc how you are supposed to log into the recovery silo. Try username `recovery`, password `oxide`.

https://github.com/oxidecomputer/omicron/blob/82c77f2751c57f3dc9560eea79657871ba1bafc9/smf/sled-agent/non-gimlet/config-rss.toml#L133-L146

If this works, then it would make perfect sense to me to add this to the omicron doc.
